In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#libraries

# Data

In [ ]:
df1=pd.read_csv("PersonalFinance.csv")

#calling data

In [ ]:
df1.head()

Customer ID  Gender  Age  Annual Income(k$)  Spending Score (1 - 100)
0            1    Male   19                 15                        39
1            2    Male   21                 15                        81
2            3  Female   20                 16                         6
3            4  Female   23                 16                        77
4            5  Female   31                 17                        40

spending score is the target variable.

In [ ]:
df1

#full data set


Customer ID  Gender  Age  Annual Income(k$)  Spending Score (1 - 100)
0            1    Male   19                 15                        39
1            2    Male   21                 15                        81
2            3  Female   20                 16                         6
3            4  Female   23                 16                        77
4            5  Female   31                 17                        40

In [ ]:
df1.shape

(5, 5)

In [ ]:
df1.columns

Index(['Customer ID', 'Gender', 'Age', 'Annual Income(k$)',
       'Spending Score (1 - 100)'],
      dtype='object')

In [ ]:
df1.dtypes

Customer ID                  int64
Gender                      object
Age                          int64
Annual Income(k$)            int64
Spending Score (1 - 100)     int64
dtype: object

In [ ]:
df1["Spending Score (1 - 100)"]

0    39
1    81
2     6
3    77
4    40
Name: Spending Score (1 - 100), dtype: int64

# Data feature Engineering

In [ ]:
df1["Age"]

0    19
1    21
2    20
3    23
4    31
Name: Age, dtype: int64

In [ ]:
df=df1.copy()

In [ ]:
df["Age"]**2
#squaring age

0    361
1    441
2    400
3    529
4    961
Name: Age, dtype: int64

In [ ]:
df["New feature"]=df["Age"]*df["Annual Income(k$)"]
df

#adding a new feature too the data.
#feature engineering
#product of two features

Customer ID  Gender  Age  Annual Income(k$)  Spending Score (1 - 100)  \
0            1    Male   19                 15                        39   
1            2    Male   21                 15                        81   
2            3  Female   20                 16                         6   
3            4  Female   23                 16                        77   
4            5  Female   31                 17                        40   

   New feature  
0          285  
1          315  
2          320  
3          368  
4          527

In [ ]:
df=df.rename(columns={"Annual Income(k$)":"Annual Income", "Spending Score (1 - 100)":"Spending Score"})
#renaming feature

In [ ]:
df

Customer ID  Gender  Age  Annual Income  Spending Score  New feature
0            1    Male   19             15              39          285
1            2    Male   21             15              81          315
2            3  Female   20             16               6          320
3            4  Female   23             16              77          368
4            5  Female   31             17              40          527

In [ ]:
df.drop(columns=["New feature"],inplace=True)

#df.drop(columns=["New feature"])
#the above another option is for temporary droping(without using df=)
#to remove a feature
#use inplace=True for delete the feature permenantly


df

Customer ID  Gender  Age  Annual Income  Spending Score
0            1    Male   19             15              39
1            2    Male   21             15              81
2            3  Female   20             16               6
3            4  Female   23             16              77
4            5  Female   31             17              40

# EDA- Exploratory Data Analysis

# Train Test Split

In [ ]:
y=df["Spending Score"]   #extracting target variable column
x=df.drop(columns=["Spending Score"]) #extracting training column

In [ ]:
y

0    39
1    81
2     6
3    77
4    40
Name: Spending Score, dtype: int64

In [ ]:
x

Customer ID  Gender  Age  Annual Income
0            1    Male   19             15
1            2    Male   21             15
2            3  Female   20             16
3            4  Female   23             16
4            5  Female   31             17

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.2, random_state=42)
#0.2 means 20% test then 80% train


In [ ]:
print("X_train shape:", X_train.shape)
print("X_test shape:", x_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (4, 4)
X_test shape: (1, 4)
y_train shape: (4,)
y_test shape: (1,)


In [ ]:
# X_train shape: (4, 4) means 4 row 4 column(80%)

In [ ]:
X_train

Customer ID  Gender  Age  Annual Income
4            5  Female   31             17
2            3  Female   20             16
0            1    Male   19             15
3            4  Female   23             16

In [ ]:
x_test

Customer ID Gender  Age  Annual Income
1            2   Male   21             15

In [ ]:
y_train

4    40
2     6
0    39
3    77
Name: Spending Score, dtype: int64

In [ ]:
y_test

1    81
Name: Spending Score, dtype: int64

# Preprocessing

In [ ]:
# Label Encoder - to change categorical value to numerical data

from sklearn.preprocessing import LabelEncoder
labelencoder= LabelEncoder()    #object calling the class
X_train['Gender']= labelencoder.fit_transform(X_train['Gender'])
x_test['Gender']= labelencoder.fit_transform(x_test['Gender'])
#This function fit the data first then transform the data.


#print the encoded data
print(X_train)
print(x_test)

   Customer ID  Gender  Age  Annual Income
4            5       0   31             17
2            3       0   20             16
0            1       1   19             15
3            4       0   23             16
   Customer ID  Gender  Age  Annual Income
1            2       0   21             15


# Linear Models

In [ ]:
from sklearn.linear_model import LinearRegression

lr_model= LinearRegression()   #object calling
lr_model.fit(X_train, y_train)

lr_prediction= lr_model.predict(x_test)
lr_prediction



array([65.86666667])

In [ ]:
from sklearn.metrics import mean_absolute_error
lr_mae = mean_absolute_error(y_test, lr_prediction)

lr_mae

# error means actual value - predicted value

15.133333333333212

In [ ]:
y_test
# actual value is 81. But predicted value is 65.866

1    81
Name: Spending Score, dtype: int64

In [ ]:
15.13333/81

# percentage error

0.18683123456790124

In [ ]:
print("The accuracy of the linear regression model is", (65.86666667/81)*100)

The accuracy of the linear regression model is 81.31687243209876


## Removing unwanted feature

In [ ]:
X_train_custom = X_train.drop(columns=["Customer ID"])
X_test_custom = x_test.drop(columns=["Customer ID"])

In [ ]:
X_test_custom

Gender  Age  Annual Income
1       0   21             15

In [ ]:
X_train_custom

Gender  Age  Annual Income
4       0   31             17
2       0   20             16
0       1   19             15
3       0   23             16

In [ ]:
from sklearn.linear_model import LinearRegression

lr_model= LinearRegression()   #object calling
lr_model.fit(X_train_custom, y_train)

lr_prediction_custom= lr_model.predict(X_test_custom)
lr_prediction_custom



array([256.])

In [ ]:
from sklearn.metrics import mean_absolute_error
lr_mae = mean_absolute_error(y_test, lr_prediction)

lr_mae

# error means actual value - predicted value

15.133333333333212

# DecisionTreeRegressor

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

dt_model= DecisionTreeRegressor()       #calling object of model class
dt_model.fit(X_train, y_train)             #training the model by fitting
dt_prediction= dt_model.predict(x_test)    #predicting unknown data
dt_mae= mean_absolute_error(y_test, dt_prediction)
print("prediction value : ", dt_prediction)
print("MAE:", dt_mae)
mean_sqrd_error_dt=mean_squared_error(y_test, dt_prediction)
print("Mean squared error: ", mean_sqrd_error_dt)


prediction value :  [6.]
MAE: 75.0
Mean squared error:  5625.0


# SVR - Support Vector Regressor

In [ ]:
from sklearn.svm import SVR
svm_model = SVR(kernel='sigmoid')
#linear, poly , rbf, sigmoid, precomputed
svm_model.fit(X_train,y_train)
svm_prediction=svm_model.predict(x_test)
print("SVM Prediction: ",svm_prediction)

from sklearn.metrics import mean_absolute_error
svm_mae = mean_absolute_error(y_test,svm_prediction)
print("SVM Mean absolute error: ",svm_mae)

SVM Prediction:  [39.51683573]
SVM Mean absolute error:  41.48316427323584


In [ ]:
from sklearn.svm import SVR
svm_model = SVR(kernel='poly')
#linear, poly , rbf, sigmoid, precomputed
svm_model.fit(X_train,y_train)
svm_prediction=svm_model.predict(x_test)
print("SVM Prediction: ",svm_prediction)

from sklearn.metrics import mean_absolute_error
svm_mae = mean_absolute_error(y_test,svm_prediction)
print("SVM Mean absolute error: ",svm_mae)

SVM Prediction:  [39.02997374]
SVM Mean absolute error:  41.97002626467404


In [ ]:
from sklearn.svm import SVR
svm_model = SVR(kernel='linear')
#linear, poly , rbf, sigmoid, precomputed
svm_model.fit(X_train,y_train)
svm_prediction=svm_model.predict(x_test)
print("SVM Prediction: ",svm_prediction)

from sklearn.metrics import mean_absolute_error
svm_mae = mean_absolute_error(y_test,svm_prediction)
print("SVM Mean absolute error: ",svm_mae)

SVM Prediction:  [39.08060606]
SVM Mean absolute error:  41.919393939393984


# Standardisation (Scaling)

To make all data in each feature to a standard range scale.


In Gender, highest value is 1 and lowest is 0. Range is 1-0=1. In Age maximum is 31 and lowest is 19. So Range is 12. These should be in a common scale. So use StandardScaler

scaled data z=(data-mean)/std

In [ ]:
X1_train, x1_test, y1_train, y1_test= train_test_split(x,y, test_size=0.4, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
std_scaler= StandardScaler()
X1_train, x1_test, y1_train, y1_test= train_test_split(x,y, test_size=0.4, random_state=42)

X1_train['Gender']= labelencoder.fit_transform(X1_train['Gender'])
x1_test['Gender']= labelencoder.fit_transform(x1_test['Gender'])


X1_train_scaled= pd.DataFrame(std_scaler.fit_transform(X1_train),
                             columns=X1_train.columns, index=X1_train.index)
x1_test_scaled= pd.DataFrame(std_scaler.fit_transform(x1_test),
                             columns=x1_test.columns, index = x1_test.index)


print(X1_train_scaled)

#Normal distribution

   Customer ID    Gender       Age  Annual Income
2     0.267261 -0.707107 -0.392232       0.707107
0    -1.336306  1.414214 -0.980581      -1.414214
3     1.069045 -0.707107  1.372813       0.707107


In [ ]:
print(x1_test_scaled)

   Customer ID  Gender  Age  Annual Income
1         -1.0     1.0 -1.0           -1.0
4          1.0    -1.0  1.0            1.0


## LinearRegression after scaling

In [ ]:
from sklearn.linear_model import LinearRegression

lr_model_scaled= LinearRegression()   #object calling
lr_model_scaled.fit(X1_train_scaled, y1_train)

lr_prediction_scaled= lr_model_scaled.predict(x1_test_scaled)
lr_prediction_scaled



array([27.74491059, 53.58842274])

In [ ]:
lr_mae_scaled = mean_absolute_error(y1_test, lr_prediction_scaled)

lr_mae_scaled

# error means actual value - predicted value

33.42175607723677

## DecisionTreeRegressor after scaling

> Add blockquote



In [ ]:
dt_model= DecisionTreeRegressor()       #calling object of model class
dt_model.fit(X1_train_scaled, y1_train)             #training the model by fitting
dt_prediction_scaled= dt_model.predict(x1_test_scaled)    #predicting unknown data
dt_mae_scaled= mean_absolute_error(y1_test, dt_prediction_scaled)
print("prediction value after scaling: ", dt_prediction_scaled)
print("MAE:", dt_mae_scaled)
mean_sqrd_error_dt_scaled=mean_squared_error(y1_test, dt_prediction_scaled)
print("Mean squared error: ", mean_sqrd_error_dt_scaled)


prediction value after scaling:  [39. 77.]
MAE: 39.5
Mean squared error:  1566.5


## SVR after scaling

In [ ]:
svm_model = SVR(kernel='sigmoid')
#linear, poly , rbf, sigmoid, precomputed
svm_model.fit(X1_train_scaled,y1_train)
svm_prediction_scaled=svm_model.predict(x1_test_scaled)
print("SVM Prediction: ",svm_prediction_scaled)

from sklearn.metrics import mean_absolute_error
svm_mae_scaled = mean_absolute_error(y1_test,svm_prediction_scaled)
print("SVM Mean absolute error: ",svm_mae_scaled)

SVM Prediction:  [38.94054947 39.80948743]
SVM Mean absolute error:  21.124981552362442
